# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'status.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_status(object):
    def setupUi(self, status):
        status.setObjectName("status")
        status.resize(609, 531)
        self.label = QtWidgets.QLabel(status)
        self.label.setGeometry(QtCore.QRect(50, 130, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(status)
        self.label_2.setGeometry(QtCore.QRect(260, 30, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(status)
        self.label_3.setGeometry(QtCore.QRect(50, 200, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.textEdit = QtWidgets.QTextEdit(status)
        self.textEdit.setGeometry(QtCore.QRect(40, 230, 521, 31))
        self.textEdit.setObjectName("textEdit")
        self.verticalLayoutWidget = QtWidgets.QWidget(status)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(210, 130, 111, 41))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lcd_volt = QtWidgets.QLCDNumber(self.verticalLayoutWidget)
        self.lcd_volt.setObjectName("lcd_volt")
        self.verticalLayout_2.addWidget(self.lcd_volt)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(status)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(210, 180, 121, 41))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_uv = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_uv.setFont(font)
        self.label_uv.setObjectName("label_uv")
        self.verticalLayout_3.addWidget(self.label_uv)

        self.retranslateUi(status)
        QtCore.QMetaObject.connectSlotsByName(status)

    def retranslateUi(self, status):
        _translate = QtCore.QCoreApplication.translate
        status.setWindowTitle(_translate("status", "Status Robot"))
        self.label.setText(_translate("status", "Tegangan Robot"))
        self.label_2.setText(_translate("status", "SPERO"))
        self.label_3.setText(_translate("status", "UV - C"))
        self.label_uv.setText(_translate("status", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    status = QtWidgets.QWidget()
    ui = Ui_status()
    ui.setupUi(status)
    status.show()
    sys.exit(app.exec_())
